INSERT INTO "user"(username, password)
       VALUES ('gisel','2006'), ('aymara','celular'),('jesica', '1706'), 
	   ('carolina', 'barato');


INSERT INTO "post"(author_id, title, body) 
       VALUES ('1', 'bibliotecaria', 'trabaja de atencion al publico'), 
	          ('2', 'profesora', 'trabaja de ayudante'),
			  ('3', 'remisero', 'trabaja en el trasporte publico'),
			  ('4', 'tecnico', 'trabaja en el servicio tecnico');


/* falta verificar 